import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/contexts/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/hooks/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/lib/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/styles/**/*.{css,ts}",
  ],
  theme: {
    extend: {
      colors: {
        "elv-indigo": "#686BE0",
        "elv-violet": "#8C8EFF",
        "elv-purple": "#A5A6FF",
        "elv-iris": "#8C8EFF",
        "elv-success": "#059669",
        "elv-warning": "#D97706",
        "elv-danger": "#DC2626",
        "elv-info": "#0284C7",
        "elv-base": "#F8F9FF",
        "elv-surface": "#FFFFFF",
        "elv-surface-2": "#F0F0FF",
        "elv-border": "#D8D9FF",
        "elv-dark-base": "#0D0D1A",
        "elv-dark-1": "#13132B",
        "elv-dark-2": "#1C1C3A",
        "elv-dark-3": "#252547",
        "elv-dark-border": "#2E2E5A",
        "elv-text": "#1A1A3E",
        "elv-text-2": "#4A4A7A",
        "elv-text-3": "#8888AA",
        "elv-text-inv": "#FFFFFF",
        brand: {
          50: "#F7F7FF",
          100: "#F0F0FF",
          200: "#D8D9FF",
          300: "#BFC0FF",
          400: "#A5A6FF",
          500: "#8C8EFF",
          600: "#7A7CF2",
          700: "#686BE0",
          800: "#5558B8",
          900: "#3D3F85",
          950: "#252747",
        },
        trust: {
          DEFAULT: "var(--trust)",
          foreground: "var(--trust-foreground)",
          subtle: "var(--trust-subtle)",
        },
        background: "var(--background)",
        foreground: "var(--foreground)",
        overlay: "var(--overlay)",
        glass: {
          DEFAULT: "var(--glass)",
          muted: "var(--glass-muted)",
          border: "var(--glass-border)",
          strong: "var(--glass-strong)",
        },
        text: {
          primary: "var(--text-primary)",
          secondary: "var(--text-secondary)",
          tertiary: "var(--text-tertiary)",
          inverse: "var(--text-inverse)",
        },
        accent: {
          DEFAULT: "var(--accent)",
          foreground: "var(--accent-foreground)",
          subtle: "var(--accent-subtle)",
        },
        primary: {
          DEFAULT: "var(--primary)",
          foreground: "var(--primary-foreground)",
          container: "var(--primary-container)",
          subtle: "var(--primary-subtle)",
          ring: "var(--primary-ring)",
        },
        secondary: {
          DEFAULT: "var(--secondary)",
          foreground: "var(--secondary-foreground)",
          container: "var(--secondary-container)",
          subtle: "var(--secondary-subtle)",
        },
        success: {
          DEFAULT: "var(--success)",
          foreground: "var(--success-foreground)",
          container: "var(--success-container)",
          subtle: "var(--success-subtle)",
        },
        warning: {
          DEFAULT: "var(--warning)",
          foreground: "var(--warning-foreground)",
          container: "var(--warning-container)",
          subtle: "var(--warning-subtle)",
        },
        danger: {
          DEFAULT: "var(--danger)",
          foreground: "var(--danger-foreground)",
          container: "var(--danger-container)",
          subtle: "var(--danger-subtle)",
        },
        info: {
          DEFAULT: "var(--info)",
          foreground: "var(--info-foreground)",
          container: "var(--info-container)",
          subtle: "var(--info-subtle)",
        },
        verified: {
          DEFAULT: "var(--verified)",
          foreground: "var(--verified-foreground)",
          container: "var(--verified-container)",
          subtle: "var(--verified-subtle)",
        },
        escrow: {
          DEFAULT: "var(--escrow)",
          foreground: "var(--escrow-foreground)",
          container: "var(--escrow-container)",
          subtle: "var(--escrow-subtle)",
        },
        review: {
          DEFAULT: "var(--review)",
          foreground: "var(--review-foreground)",
          container: "var(--review-container)",
          subtle: "var(--review-subtle)",
        },
        risk: {
          DEFAULT: "var(--risk)",
          foreground: "var(--risk-foreground)",
          container: "var(--risk-container)",
          subtle: "var(--risk-subtle)",
        },
        surface: {
          DEFAULT: "var(--surface)",
          muted: "var(--surface-muted)",
          raised: "var(--surface-raised)",
          sunken: "var(--surface-sunken)",
          overlay: "var(--surface-overlay)",
          inverse: "var(--surface-inverse)",
        },
        border: {
          DEFAULT: "var(--border)",
          subtle: "var(--border-subtle)",
          strong: "var(--border-strong)",
        },
        chart: {
          primary: "var(--chart-primary)",
          secondary: "var(--chart-secondary)",
          tertiary: "var(--chart-tertiary)",
          success: "var(--chart-success)",
          warning: "var(--chart-warning)",
          danger: "var(--chart-danger)",
          grid: "var(--chart-grid)",
          axis: "var(--chart-axis)",
        },
        control: {
          DEFAULT: "var(--control)",
          hover: "var(--control-hover)",
          active: "var(--control-active)",
          border: "var(--control-border)",
        },
        table: {
          header: "var(--table-header)",
          row: "var(--table-row)",
          rowHover: "var(--table-row-hover)",
          border: "var(--table-border)",
        },
        sidebar: {
          DEFAULT: "var(--sidebar)",
          foreground: "var(--sidebar-foreground)",
          border: "var(--sidebar-border)",
          active: "var(--sidebar-active)",
        },
        topbar: {
          DEFAULT: "var(--topbar)",
          foreground: "var(--topbar-foreground)",
          border: "var(--topbar-border)",
        },
        modal: {
          DEFAULT: "var(--modal)",
          overlay: "var(--modal-overlay)",
          border: "var(--modal-border)",
        },
        toast: {
          DEFAULT: "var(--toast)",
          foreground: "var(--toast-foreground)",
          border: "var(--toast-border)",
        },
        empty: {
          DEFAULT: "var(--empty)",
          foreground: "var(--empty-foreground)",
          border: "var(--empty-border)",
        },
        skeleton: {
          base: "var(--skeleton-base)",
          shine: "var(--skeleton-shine)",
        },
        ring: "var(--ring)",
        muted: {
          DEFAULT: "var(--muted)",
          foreground: "var(--muted-foreground)",
        },
      },
      fontFamily: {
        sans: ["var(--font-sans)"],
        mono: ["var(--font-mono)"],
      },
      fontSize: {
        xs: "var(--text-xs)",
        sm: "var(--text-sm)",
        base: "var(--text-base)",
        lg: "var(--text-lg)",
        xl: "var(--text-xl)",
        "2xl": "var(--text-2xl)",
        "3xl": "var(--text-3xl)",
        "4xl": "var(--text-4xl)",
        "5xl": "var(--text-5xl)",
        "6xl": "var(--text-6xl)",
        h1: ["var(--text-4xl)", { lineHeight: "1.12", fontWeight: "700", letterSpacing: "0" }],
        h2: ["var(--text-3xl)", { lineHeight: "1.18", fontWeight: "700", letterSpacing: "0" }],
        h3: ["var(--text-2xl)", { lineHeight: "1.24", fontWeight: "700", letterSpacing: "0" }],
        h4: ["var(--text-xl)", { lineHeight: "1.3", fontWeight: "700", letterSpacing: "0" }],
        h5: ["var(--text-lg)", { lineHeight: "1.4", fontWeight: "700", letterSpacing: "0" }],
        h6: ["var(--text-base)", { lineHeight: "1.5", fontWeight: "700", letterSpacing: "0" }],
        display: ["var(--text-display)", { lineHeight: "var(--leading-display)", fontWeight: "800", letterSpacing: "0" }],
        "title-lg": ["var(--text-title-lg)", { lineHeight: "var(--leading-title)", fontWeight: "800", letterSpacing: "0" }],
        "title-md": ["var(--text-title-md)", { lineHeight: "var(--leading-title)", fontWeight: "750", letterSpacing: "0" }],
        "title-sm": ["var(--text-title-sm)", { lineHeight: "var(--leading-title)", fontWeight: "750", letterSpacing: "0" }],
        body: ["var(--text-base)", { lineHeight: "1.5", fontWeight: "400" }],
        "body-sm": ["var(--text-sm)", { lineHeight: "1.45", fontWeight: "400" }],
        caption: ["var(--text-xs)", { lineHeight: "1.35", fontWeight: "500" }],
        label: ["var(--text-xs)", { lineHeight: "1.35", fontWeight: "600", letterSpacing: "0" }],
        micro: ["0.6875rem", { lineHeight: "0.875rem", fontWeight: "600", letterSpacing: "0" }],
      },
      lineHeight: {
        tight: "var(--leading-tight)",
        snug: "var(--leading-snug)",
        normal: "var(--leading-normal)",
        relaxed: "var(--leading-relaxed)",
        display: "var(--leading-display)",
        title: "var(--leading-title)",
      },
      letterSpacing: {
        tight: "var(--tracking-tight)",
        normal: "var(--tracking-normal)",
        wide: "var(--tracking-wide)",
        wider: "var(--tracking-wider)",
      },
      spacing: {
        px: "1px",
        0.5: "2px",
        1: "4px",
        1.5: "6px",
        2: "8px",
        2.5: "10px",
        3: "12px",
        3.5: "14px",
        4: "16px",
        5: "20px",
        6: "24px",
        7: "28px",
        8: "32px",
        9: "36px",
        10: "40px",
        12: "48px",
        14: "56px",
        16: "64px",
        18: "72px",
        20: "80px",
        24: "96px",
        28: "112px",
        32: "128px",
        36: "144px",
        40: "160px",
        "card-gap": "24px",
        control: "var(--control-height)",
        "control-sm": "var(--control-height-sm)",
        "control-lg": "var(--control-height-lg)",
        section: "32px",
        mobile: "16px",
        sidebar: "260px",
        "sidebar-collapsed": "72px",
      },
      maxWidth: {
        content: "1440px",
      },
      borderRadius: {
        xs: "var(--radius-xs)",
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        "2xl": "var(--radius-2xl)",
        full: "var(--radius-full)",
      },
      boxShadow: {
        sm: "var(--shadow-sm)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
        xl: "var(--shadow-xl)",
        "2xl": "var(--shadow-2xl)",
        glow: "var(--shadow-glow)",
        glass: "var(--shadow-glass)",
        focus: "var(--shadow-focus)",
        card: "var(--shadow-card)",
        floating: "var(--shadow-floating)",
        table: "var(--shadow-table)",
        modal: "var(--shadow-modal)",
        toast: "var(--shadow-toast)",
      },
      backgroundImage: {
        "elv-mesh": "var(--gradient-mesh)",
        "elv-surface": "var(--gradient-surface)",
        "elv-primary": "var(--gradient-primary)",
        "elv-trust": "var(--gradient-trust)",
        "elv-glass": "var(--gradient-glass)",
      },
      ringColor: {
        DEFAULT: "var(--ring)",
      },
    },
  },
};

export default config;
