export const elvDesignTokens = {
  color: {
    background: "var(--background)",
    foreground: "var(--foreground)",
    surface: "var(--surface)",
    surfaceMuted: "var(--surface-muted)",
    surfaceRaised: "var(--surface-raised)",
    surfaceSunken: "var(--surface-sunken)",
    surfaceOverlay: "var(--surface-overlay)",
    surfaceInverse: "var(--surface-inverse)",
    glass: "var(--glass)",
    glassMuted: "var(--glass-muted)",
    glassBorder: "var(--glass-border)",
    glassStrong: "var(--glass-strong)",
    border: "var(--border)",
    borderSubtle: "var(--border-subtle)",
    borderStrong: "var(--border-strong)",
    textPrimary: "var(--text-primary)",
    textSecondary: "var(--text-secondary)",
    textTertiary: "var(--text-tertiary)",
    textInverse: "var(--text-inverse)",
    primary: "var(--primary)",
    primaryForeground: "var(--primary-foreground)",
    primaryContainer: "var(--primary-container)",
    primarySubtle: "var(--primary-subtle)",
    secondary: "var(--secondary)",
    secondaryForeground: "var(--secondary-foreground)",
    secondaryContainer: "var(--secondary-container)",
    secondarySubtle: "var(--secondary-subtle)",
    accent: "var(--accent)",
    accentForeground: "var(--accent-foreground)",
    accentSubtle: "var(--accent-subtle)",
    trust: "var(--trust)",
    trustForeground: "var(--trust-foreground)",
    trustSubtle: "var(--trust-subtle)",
  },
  status: {
    success: {
      base: "var(--success)",
      foreground: "var(--success-foreground)",
      container: "var(--success-container)",
      subtle: "var(--success-subtle)",
    },
    warning: {
      base: "var(--warning)",
      foreground: "var(--warning-foreground)",
      container: "var(--warning-container)",
      subtle: "var(--warning-subtle)",
    },
    danger: {
      base: "var(--danger)",
      foreground: "var(--danger-foreground)",
      container: "var(--danger-container)",
      subtle: "var(--danger-subtle)",
    },
    info: {
      base: "var(--info)",
      foreground: "var(--info-foreground)",
      container: "var(--info-container)",
      subtle: "var(--info-subtle)",
    },
    verified: {
      base: "var(--verified)",
      foreground: "var(--verified-foreground)",
      container: "var(--verified-container)",
      subtle: "var(--verified-subtle)",
    },
    escrow: {
      base: "var(--escrow)",
      foreground: "var(--escrow-foreground)",
      container: "var(--escrow-container)",
      subtle: "var(--escrow-subtle)",
    },
    review: {
      base: "var(--review)",
      foreground: "var(--review-foreground)",
      container: "var(--review-container)",
      subtle: "var(--review-subtle)",
    },
    risk: {
      base: "var(--risk)",
      foreground: "var(--risk-foreground)",
      container: "var(--risk-container)",
      subtle: "var(--risk-subtle)",
    },
  },
  chart: {
    primary: "var(--chart-primary)",
    secondary: "var(--chart-secondary)",
    tertiary: "var(--chart-tertiary)",
    success: "var(--chart-success)",
    warning: "var(--chart-warning)",
    danger: "var(--chart-danger)",
    grid: "var(--chart-grid)",
    axis: "var(--chart-axis)",
  },
  typography: {
    family: {
      sans: "var(--font-sans)",
      mono: "var(--font-mono)",
    },
    size: {
      micro: "var(--text-micro)",
      xs: "var(--text-xs)",
      sm: "var(--text-sm)",
      base: "var(--text-base)",
      lg: "var(--text-lg)",
      xl: "var(--text-xl)",
      "2xl": "var(--text-2xl)",
      "3xl": "var(--text-3xl)",
      "4xl": "var(--text-4xl)",
      "5xl": "var(--text-5xl)",
      "6xl": "var(--text-6xl)",
      display: "var(--text-display)",
      titleLg: "var(--text-title-lg)",
      titleMd: "var(--text-title-md)",
      titleSm: "var(--text-title-sm)",
    },
    leading: {
      tight: "var(--leading-tight)",
      snug: "var(--leading-snug)",
      normal: "var(--leading-normal)",
      relaxed: "var(--leading-relaxed)",
      display: "var(--leading-display)",
      title: "var(--leading-title)",
    },
    tracking: {
      tight: "var(--tracking-tight)",
      normal: "var(--tracking-normal)",
      wide: "var(--tracking-wide)",
      wider: "var(--tracking-wider)",
    },
  },
  space: {
    0: "var(--space-0)",
    "0.5": "var(--space-0-5)",
    1: "var(--space-1)",
    "1.5": "var(--space-1-5)",
    2: "var(--space-2)",
    "2.5": "var(--space-2-5)",
    3: "var(--space-3)",
    "3.5": "var(--space-3-5)",
    4: "var(--space-4)",
    5: "var(--space-5)",
    6: "var(--space-6)",
    7: "var(--space-7)",
    8: "var(--space-8)",
    9: "var(--space-9)",
    10: "var(--space-10)",
    12: "var(--space-12)",
    14: "var(--space-14)",
    16: "var(--space-16)",
    20: "var(--space-20)",
    24: "var(--space-24)",
    32: "var(--space-32)",
    cardGap: "var(--card-gap)",
    section: "var(--section-padding)",
    mobile: "var(--mobile-padding)",
    controlSm: "var(--control-height-sm)",
    control: "var(--control-height)",
    controlLg: "var(--control-height-lg)",
  },
  radius: {
    xs: "var(--radius-xs)",
    sm: "var(--radius-sm)",
    md: "var(--radius-md)",
    lg: "var(--radius-lg)",
    xl: "var(--radius-xl)",
    "2xl": "var(--radius-2xl)",
    full: "var(--radius-full)",
  },
  shadow: {
    xs: "var(--shadow-xs)",
    sm: "var(--shadow-sm)",
    md: "var(--shadow-md)",
    lg: "var(--shadow-lg)",
    xl: "var(--shadow-xl)",
    "2xl": "var(--shadow-2xl)",
    card: "var(--shadow-card)",
    floating: "var(--shadow-floating)",
    glass: "var(--shadow-glass)",
    glow: "var(--shadow-glow)",
    focus: "var(--shadow-focus)",
    table: "var(--shadow-table)",
    modal: "var(--shadow-modal)",
    toast: "var(--shadow-toast)",
  },
  gradient: {
    primary: "var(--gradient-primary)",
    trust: "var(--gradient-trust)",
    surface: "var(--gradient-surface)",
    glass: "var(--gradient-glass)",
    mesh: "var(--gradient-mesh)",
  },
  layout: {
    contentMaxWidth: "var(--content-max-width)",
    sidebarWidth: "var(--sidebar-width)",
    sidebarCollapsedWidth: "var(--sidebar-collapsed-width)",
  },
} as const;

export const elvPatterns = {
  page: "elv-page",
  container: "elv-container",
  section: "elv-section",
  stack: "elv-stack",
  kicker: "elv-kicker",
  headingDisplay: "elv-heading-display",
  headingSection: "elv-heading-section",
  muted: "elv-muted",
  gradientText: "elv-gradient-text",
  card: "elv-card",
  panel: "elv-panel",
  glass: "elv-glass",
  glassCard: "elv-glass-card",
  interactive: "elv-interactive",
  focusRing: "elv-focus-ring",
  button: "elv-button",
  buttonPrimary: "elv-button elv-button-primary",
  buttonSecondary: "elv-button elv-button-secondary",
  buttonGhost: "elv-button elv-button-ghost",
  badge: "elv-badge",
  badgeSuccess: "elv-badge elv-badge-success",
  badgeWarning: "elv-badge elv-badge-warning",
  badgeDanger: "elv-badge elv-badge-danger",
  badgeInfo: "elv-badge elv-badge-info",
  badgeTrust: "elv-badge elv-badge-trust",
  field: "elv-field",
  label: "elv-label",
  input: "elv-input",
  select: "elv-select",
  textarea: "elv-textarea",
  table: "elv-table",
  sidebar: "elv-sidebar",
  topbar: "elv-topbar",
  modal: "elv-modal",
  toast: "elv-toast",
  emptyState: "elv-empty-state",
  chartPanel: "elv-chart-panel",
  skeleton: "elv-skeleton",
  dashboardGrid: "elv-dashboard-grid",
  commandSurface: "elv-command-surface",
} as const;

export type ElvDesignTokens = typeof elvDesignTokens;
export type ElvColorToken = keyof ElvDesignTokens["color"];
export type ElvStatusToken = keyof ElvDesignTokens["status"];
export type ElvChartToken = keyof ElvDesignTokens["chart"];
export type ElvRadiusToken = keyof ElvDesignTokens["radius"];
export type ElvShadowToken = keyof ElvDesignTokens["shadow"];
export type ElvSpaceToken = keyof ElvDesignTokens["space"];
export type ElvPatternToken = keyof typeof elvPatterns;
