export const vendors = [
  {
    id: "vendor-secure-vision",
    name: "Secure Vision Systems",
    category: "CCTV",
    city: "Delhi NCR",
    rating: 4.8,
    score: 92,
    response: "18 min",
    responseMinutes: 18,
    radius: "60 km",
    distance: 8.4,
    projectCount: 148,
    certifications: ["CP Plus", "Hikvision", "ISO 9001"],
  },
  {
    id: "vendor-fire-grid",
    name: "FireGrid Safety Works",
    category: "Fire",
    city: "Gurugram",
    rating: 4.7,
    score: 89,
    response: "24 min",
    responseMinutes: 24,
    radius: "45 km",
    distance: 12.6,
    projectCount: 112,
    certifications: ["NBC Compliance", "Honeywell", "Bosch"],
  },
  {
    id: "vendor-fiber-link",
    name: "FiberLink Networks",
    category: "Networking",
    city: "Noida",
    rating: 4.6,
    score: 86,
    response: "31 min",
    responseMinutes: 31,
    radius: "75 km",
    distance: 16.1,
    projectCount: 96,
    certifications: ["Cisco", "CommScope", "Fluke Tested"],
  },
  {
    id: "vendor-access-axis",
    name: "Access Axis Automation",
    category: "Access Control",
    city: "Delhi NCR",
    rating: 4.9,
    score: 94,
    response: "21 min",
    responseMinutes: 21,
    radius: "55 km",
    distance: 10.2,
    projectCount: 124,
    certifications: ["HID", "ZKTeco", "Boom Barrier Specialist"],
  },
  {
    id: "vendor-bms-nexus",
    name: "BMS Nexus Integrators",
    category: "BMS",
    city: "Faridabad",
    rating: 4.5,
    score: 84,
    response: "38 min",
    responseMinutes: 38,
    radius: "80 km",
    distance: 22.8,
    projectCount: 78,
    certifications: ["Johnson Controls", "BACnet", "Energy Audit"],
  },
];

export const projects = [
  {
    id: "project-factory-cctv",
    title: "Factory CCTV deployment",
    category: "CCTV",
    location: "Manesar, Haryana",
    budget: "Rs 2.4L",
    status: "in_progress",
    progress: 60,
    vendor: "Secure Vision Systems",
    delayRisk: "medium",
  },
  {
    id: "project-fire-noc",
    title: "Fire NOC readiness",
    category: "Fire",
    location: "Delhi NCR",
    budget: "Rs 1.1L",
    status: "delayed",
    progress: 40,
    vendor: "FireGrid Safety Works",
    delayRisk: "high",
  },
  {
    id: "project-office-network",
    title: "Office structured cabling",
    category: "Networking",
    location: "Noida",
    budget: "Rs 1.8L",
    status: "completed",
    progress: 100,
    vendor: "FiberLink Networks",
    delayRisk: "low",
  },
];

export const milestones = [
  { stage: "survey", status: "completed", proof: "Survey report uploaded" },
  { stage: "quote", status: "completed", proof: "BOQ approved" },
  { stage: "installation", status: "in_progress", proof: "16 cameras mounted" },
  { stage: "testing", status: "pending", proof: "Awaiting NVR test" },
  { stage: "handover", status: "pending", proof: "Pending documents" },
];
