export const tokens = {
  colors: {
    elvIndigo: "var(--elv-indigo)",
    elvViolet: "var(--elv-violet)",
    elvPurple: "var(--elv-purple)",
    elvIris: "var(--elv-iris)",
    elvSuccess: "var(--elv-success)",
    elvWarning: "var(--elv-warning)",
    elvDanger: "var(--elv-danger)",
    elvInfo: "var(--elv-info)",
    elvBase: "var(--elv-base)",
    elvSurface: "var(--elv-surface)",
    elvSurface2: "var(--elv-surface-2)",
    elvBorder: "var(--elv-border)",
    elvText: "var(--elv-text)",
    elvText2: "var(--elv-text-2)",
    elvText3: "var(--elv-text-3)",
    elvTextInverse: "var(--elv-text-inv)",
    primary: "var(--primary)",
    primarySoft: "var(--primary-container)",
    primarySubtle: "var(--primary-subtle)",
    secondary: "var(--secondary)",
    success: "var(--success)",
    warning: "var(--warning)",
    danger: "var(--danger)",
    surface: "var(--surface)",
    surfaceRaised: "var(--surface-raised)",
    surfaceMuted: "var(--surface-muted)",
    border: "var(--border)",
    text: "var(--foreground)",
    muted: "var(--muted-foreground)",
  },
  radius: {
    xs: "var(--radius-xs)",
    sm: "var(--radius-sm)",
    md: "var(--radius-md)",
    lg: "var(--radius-lg)",
    xl: "var(--radius-xl)",
    "2xl": "var(--radius-2xl)",
  },
  shadow: {
    xs: "var(--shadow-xs)",
    sm: "var(--shadow-sm)",
    md: "var(--shadow-md)",
    lg: "var(--shadow-lg)",
    focus: "var(--shadow-focus)",
  },
} as const;

export type Tokens = typeof tokens;
